# SPDX-License-Identifier: Apache-2.0
"""Config module for kaizen-3c-cli v0.4.0.

Provides a platform-appropriate config directory, TOML read/write helpers,
and `apply_defaults` for injecting persisted settings into argparse Namespaces.

Precedence (highest wins):
    explicit CLI flag -> env var -> config.toml -> argparse defaults

`apply_defaults` only handles the config.toml -> argparse-defaults layer.
Env vars are already consumed by the pipeline scripts and the OS; we do not
touch them here (ANTHROPIC_API_KEY, OPENAI_API_KEY, etc. remain as-is).

Trade-off: detecting "flag was not explicitly set" is impossible in standard
argparse without a secondary sentinel approach.  This module uses a pragmatic
heuristic: only override if the current value equals the *known* argparse
default for that flag.  If a user explicitly passes the same value as the
default (e.g. ``--provider anthropic`` when anthropic is already the default),
the config will still override, which is an acceptable edge case given that
the outcome is identical.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import platformdirs

# ---------------------------------------------------------------------------
# TOML reader -- stdlib 3.11+, fallback to tomli for 3.10
# ---------------------------------------------------------------------------
try:
    import tomllib  # type: ignore[import]
except ImportError:
    try:
        import tomli as tomllib  # type: ignore[import,no-redef]
    except ImportError:
        tomllib = None  # type: ignore[assignment]


# ---------------------------------------------------------------------------
# Directory / path helpers
# ---------------------------------------------------------------------------


def config_dir() -> Path:
    """Return (and create) the platform-appropriate kaizen config directory.

    - Windows: ``%APPDATA%\\Local\\kaizen``  (via platformdirs)
    - macOS:   ``~/Library/Application Support/kaizen``
    - Linux:   ``$XDG_CONFIG_HOME/kaizen`` -> ``~/.config/kaizen``

    The directory is created on first access so callers can immediately write
    files without an extra ``mkdir`` call.
    """
    d = Path(platformdirs.user_config_dir("kaizen", appauthor=False))
    d.mkdir(parents=True, exist_ok=True)
    return d


def config_path() -> Path:
    """Return the path to ``config.toml`` inside ``config_dir()``."""
    return config_dir() / "config.toml"


# ---------------------------------------------------------------------------
# Load / save
# ---------------------------------------------------------------------------


def load_config() -> dict:
    """Parse ``config.toml`` and return its contents as a dict.

    Returns ``{}`` when:
    - the file does not exist (first-run scenario)
    - the file is present but empty
    - the file contains malformed TOML (logs a warning to stderr)

    Never raises; the CLI remains usable even with a corrupt config file.
    """
    path = config_path()
    if not path.exists():
        return {}

    if tomllib is None:
        print(
            "  WARN: tomllib / tomli not available; cannot read config.toml",
            file=sys.stderr,
        )
        return {}

    try:
        raw = path.read_bytes()
        if not raw.strip():
            return {}
        return tomllib.loads(raw.decode("utf-8"))
    except Exception as exc:  # noqa: BLE001 -- intentional broad catch
        print(
            f"  WARN: could not parse {path}: {exc!r}; using empty config",
            file=sys.stderr,
        )
        return {}


def save_config(config: dict) -> None:
    """Write *config* to ``config_path()`` as TOML.

    The schema is shallow (at most two-level nesting) so we hand-roll the
    serialisation rather than adding a new dependency (``tomli_w`` is not in
    stdlib; ``tomllib`` is read-only).

    Supported value types: str, int, float, bool.  Lists and deeper nesting
    are not needed by the current schema and will raise ``TypeError``.
    """
    lines: list[str] = [
        "# kaizen-3c-cli configuration -- generated by `kaizen init`",
        "# Edit manually or re-run `kaizen init` to regenerate.",
        "",
    ]

    # Separate top-level scalar keys from table sections.
    scalars = {k: v for k, v in config.items() if not isinstance(v, dict)}
    tables = {k: v for k, v in config.items() if isinstance(v, dict)}

    for key, val in scalars.items():
        lines.append(f"{key} = {_toml_value(val)}")
    if scalars:
        lines.append("")

    for section, body in tables.items():
        # Check for sub-tables inside this table.
        sub_scalars = {k: v for k, v in body.items() if not isinstance(v, dict)}
        sub_tables = {k: v for k, v in body.items() if isinstance(v, dict)}

        if sub_scalars:
            lines.append(f"[{section}]")
            for key, val in sub_scalars.items():
                lines.append(f"{key} = {_toml_value(val)}")
            lines.append("")

        for subsection, subbody in sub_tables.items():
            lines.append(f"[{section}.{subsection}]")
            for key, val in subbody.items():
                if isinstance(val, dict):
                    raise TypeError(
                        f"save_config: nesting deeper than 2 levels not supported "
                        f"(key path: {section}.{subsection}.{key})"
                    )
                lines.append(f"{key} = {_toml_value(val)}")
            lines.append("")

    path = config_path()
    path.write_text("\n".join(lines), encoding="utf-8")


def _toml_value(val: Any) -> str:
    """Render a scalar Python value as a TOML literal string."""
    if isinstance(val, bool):
        return "true" if val else "false"
    if isinstance(val, (int, float)):
        return str(val)
    if isinstance(val, str):
        # Minimal escaping: backslash and double-quote.
        escaped = val.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    raise TypeError(f"save_config: unsupported value type {type(val).__name__!r}")


# ---------------------------------------------------------------------------
# apply_defaults
# ---------------------------------------------------------------------------

# Argparse default values for each mapped flag.  If args.<attr> equals the
# value below, we treat the flag as "not explicitly set" and may override from
# config.  See module docstring for the inherent trade-off.
_ARGPARSE_DEFAULTS: dict[str, Any] = {
    "provider": "anthropic",
    "model": None,
    "adr_dir": "adrs",
    "output": None,          # context-dependent; handled per-command below
    "temperature": 0.0,
    "max_tokens": 16000,
}

# Per-command output defaults (the output flag default varies by command).
_OUTPUT_DEFAULTS_BY_COMMAND: dict[str, str] = {
    "memsafe-roadmap": "roadmap.md",
    "memsafe_roadmap": "roadmap.md",
    "migrate-plan": "plan.md",
    "migrate_plan": "plan.md",
}


def apply_defaults(
    args: argparse.Namespace,
    *,
    section: str = "default",
) -> argparse.Namespace:
    """Inject config-file values into *args* where the CLI default is still set.

    Mutates *args* in place and also returns it for chaining.

    Precedence enforced here:
        config.toml value > argparse hardcoded default

    Higher-priority layers (explicit CLI flags, env vars) are unaffected
    because we only override when ``args.<attr>`` still matches the known
    argparse default value.

    Parameters
    ----------
    args:
        The Namespace returned by ``parser.parse_args()``.
    section:
        Reserved for future per-subcommand config sections.  Currently unused;
        mapping is driven by the attribute names on *args*.
    """
    config = load_config()
    if not config:
        return args

    providers_cfg = config.get("providers", {})
    output_cfg = config.get("output", {})
    pipeline_cfg = config.get("pipeline", {})

    # --- provider -----------------------------------------------------------
    if hasattr(args, "provider") and args.provider == _ARGPARSE_DEFAULTS["provider"]:
        cfg_provider = providers_cfg.get("default")
        if cfg_provider:
            args.provider = cfg_provider

    # Resolve the effective provider (already updated above if overridden).
    effective_provider = getattr(args, "provider", _ARGPARSE_DEFAULTS["provider"])

    # --- model --------------------------------------------------------------
    if hasattr(args, "model") and args.model is _ARGPARSE_DEFAULTS["model"]:
        provider_sub = providers_cfg.get(effective_provider, {})
        if isinstance(provider_sub, dict):
            cfg_model = provider_sub.get("model")
            if cfg_model:
                args.model = cfg_model

    # --- adr_dir ------------------------------------------------------------
    if hasattr(args, "adr_dir") and args.adr_dir == _ARGPARSE_DEFAULTS["adr_dir"]:
        cfg_adr_dir = output_cfg.get("adr_dir")
        if cfg_adr_dir:
            args.adr_dir = cfg_adr_dir

    # --- output (roadmap / plan filename) -----------------------------------
    if hasattr(args, "output"):
        # Determine which default applies for this command.
        command = getattr(args, "command", "")
        expected_default = _OUTPUT_DEFAULTS_BY_COMMAND.get(command)
        if expected_default and args.output == expected_default:
            # memsafe-roadmap -> output.roadmap_filename
            if command in ("memsafe-roadmap", "memsafe_roadmap"):
                cfg_out = output_cfg.get("roadmap_filename")
            else:
                cfg_out = output_cfg.get("plan_filename")
            if cfg_out:
                args.output = cfg_out

    # --- temperature --------------------------------------------------------
    if hasattr(args, "temperature") and args.temperature == _ARGPARSE_DEFAULTS["temperature"]:
        cfg_temp = pipeline_cfg.get("temperature")
        if cfg_temp is not None:
            args.temperature = float(cfg_temp)

    # --- max_tokens (recompose only) ----------------------------------------
    if hasattr(args, "max_tokens") and args.max_tokens == _ARGPARSE_DEFAULTS["max_tokens"]:
        cfg_mt = pipeline_cfg.get("max_tokens")
        if cfg_mt is not None:
            args.max_tokens = int(cfg_mt)

    return args
